git clone command is used to bring remote repo to local workspace for the first time...
  
By using git push command we can push the changes to remote repo from local repo...

By using git pull command we can bring the changes from remote repo to local repo and it will get merged automatically..
  
git fetch command brings the changes from remote repo and stores in separate branch, we can review the changes and merge it if required...
